[build]
  command = "make build"
  functions = "functions"
  publish = "templates"
[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/fumihirokinoshita/go-chat"